# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_layer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_layer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14protocol_layer.proto\"\x86\x01\n\x05UserP\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\r\x12\x1d\n\x06gender\x18\x04 \x01(\x0e\x32\r.UserP.Gender\")\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05OTHER\x10\x02\"\x18\n\x07\x43onfigP\x12\r\n\x05\x66ield\x18\x01 \x03(\t\"\x97\x01\n\tSnapshotP\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\x04\x12\x14\n\x04pose\x18\x02 \x01(\x0b\x32\x06.PoseP\x12!\n\x0b\x63olor_image\x18\x03 \x01(\x0b\x32\x0c.ColorImageP\x12!\n\x0b\x64\x65pth_image\x18\x04 \x01(\x0b\x32\x0c.DepthImageP\x12\x1c\n\x08\x66\x65\x65lings\x18\x05 \x01(\x0b\x32\n.FeelingsP\"\xbf\x01\n\x05PoseP\x12(\n\x0btranslation\x18\x01 \x01(\x0b\x32\x13.PoseP.TranslationP\x12\"\n\x08rotation\x18\x02 \x01(\x0b\x32\x10.PoseP.RotationP\x1a/\n\x0cTranslationP\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x37\n\tRotationP\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\":\n\x0b\x43olorImageP\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\":\n\x0b\x44\x65pthImageP\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"R\n\tFeelingsP\x12\x0e\n\x06hunger\x18\x01 \x01(\x02\x12\x0e\n\x06thirst\x18\x02 \x01(\x02\x12\x12\n\nexhaustion\x18\x03 \x01(\x02\x12\x11\n\thappiness\x18\x04 \x01(\x02\x62\x06proto3'
)



_USERP_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='UserP.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_USERP_GENDER)


_USERP = _descriptor.Descriptor(
  name='UserP',
  full_name='UserP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserP.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='UserP.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='UserP.birthday', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='UserP.gender', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERP_GENDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=159,
)


_CONFIGP = _descriptor.Descriptor(
  name='ConfigP',
  full_name='ConfigP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='ConfigP.field', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=185,
)


_SNAPSHOTP = _descriptor.Descriptor(
  name='SnapshotP',
  full_name='SnapshotP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='SnapshotP.datetime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='SnapshotP.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_image', full_name='SnapshotP.color_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='SnapshotP.depth_image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='SnapshotP.feelings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=339,
)


_POSEP_TRANSLATIONP = _descriptor.Descriptor(
  name='TranslationP',
  full_name='PoseP.TranslationP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseP.TranslationP.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseP.TranslationP.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseP.TranslationP.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=476,
)

_POSEP_ROTATIONP = _descriptor.Descriptor(
  name='RotationP',
  full_name='PoseP.RotationP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseP.RotationP.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseP.RotationP.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseP.RotationP.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='PoseP.RotationP.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=533,
)

_POSEP = _descriptor.Descriptor(
  name='PoseP',
  full_name='PoseP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='PoseP.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='PoseP.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSEP_TRANSLATIONP, _POSEP_ROTATIONP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=533,
)


_COLORIMAGEP = _descriptor.Descriptor(
  name='ColorImageP',
  full_name='ColorImageP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ColorImageP.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ColorImageP.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ColorImageP.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=593,
)


_DEPTHIMAGEP = _descriptor.Descriptor(
  name='DepthImageP',
  full_name='DepthImageP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='DepthImageP.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='DepthImageP.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DepthImageP.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=653,
)


_FEELINGSP = _descriptor.Descriptor(
  name='FeelingsP',
  full_name='FeelingsP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunger', full_name='FeelingsP.hunger', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirst', full_name='FeelingsP.thirst', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exhaustion', full_name='FeelingsP.exhaustion', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happiness', full_name='FeelingsP.happiness', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=737,
)

_USERP.fields_by_name['gender'].enum_type = _USERP_GENDER
_USERP_GENDER.containing_type = _USERP
_SNAPSHOTP.fields_by_name['pose'].message_type = _POSEP
_SNAPSHOTP.fields_by_name['color_image'].message_type = _COLORIMAGEP
_SNAPSHOTP.fields_by_name['depth_image'].message_type = _DEPTHIMAGEP
_SNAPSHOTP.fields_by_name['feelings'].message_type = _FEELINGSP
_POSEP_TRANSLATIONP.containing_type = _POSEP
_POSEP_ROTATIONP.containing_type = _POSEP
_POSEP.fields_by_name['translation'].message_type = _POSEP_TRANSLATIONP
_POSEP.fields_by_name['rotation'].message_type = _POSEP_ROTATIONP
DESCRIPTOR.message_types_by_name['UserP'] = _USERP
DESCRIPTOR.message_types_by_name['ConfigP'] = _CONFIGP
DESCRIPTOR.message_types_by_name['SnapshotP'] = _SNAPSHOTP
DESCRIPTOR.message_types_by_name['PoseP'] = _POSEP
DESCRIPTOR.message_types_by_name['ColorImageP'] = _COLORIMAGEP
DESCRIPTOR.message_types_by_name['DepthImageP'] = _DEPTHIMAGEP
DESCRIPTOR.message_types_by_name['FeelingsP'] = _FEELINGSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserP = _reflection.GeneratedProtocolMessageType('UserP', (_message.Message,), {
  'DESCRIPTOR' : _USERP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:UserP)
  })
_sym_db.RegisterMessage(UserP)

ConfigP = _reflection.GeneratedProtocolMessageType('ConfigP', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:ConfigP)
  })
_sym_db.RegisterMessage(ConfigP)

SnapshotP = _reflection.GeneratedProtocolMessageType('SnapshotP', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:SnapshotP)
  })
_sym_db.RegisterMessage(SnapshotP)

PoseP = _reflection.GeneratedProtocolMessageType('PoseP', (_message.Message,), {

  'TranslationP' : _reflection.GeneratedProtocolMessageType('TranslationP', (_message.Message,), {
    'DESCRIPTOR' : _POSEP_TRANSLATIONP,
    '__module__' : 'protocol_layer_pb2'
    # @@protoc_insertion_point(class_scope:PoseP.TranslationP)
    })
  ,

  'RotationP' : _reflection.GeneratedProtocolMessageType('RotationP', (_message.Message,), {
    'DESCRIPTOR' : _POSEP_ROTATIONP,
    '__module__' : 'protocol_layer_pb2'
    # @@protoc_insertion_point(class_scope:PoseP.RotationP)
    })
  ,
  'DESCRIPTOR' : _POSEP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:PoseP)
  })
_sym_db.RegisterMessage(PoseP)
_sym_db.RegisterMessage(PoseP.TranslationP)
_sym_db.RegisterMessage(PoseP.RotationP)

ColorImageP = _reflection.GeneratedProtocolMessageType('ColorImageP', (_message.Message,), {
  'DESCRIPTOR' : _COLORIMAGEP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:ColorImageP)
  })
_sym_db.RegisterMessage(ColorImageP)

DepthImageP = _reflection.GeneratedProtocolMessageType('DepthImageP', (_message.Message,), {
  'DESCRIPTOR' : _DEPTHIMAGEP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:DepthImageP)
  })
_sym_db.RegisterMessage(DepthImageP)

FeelingsP = _reflection.GeneratedProtocolMessageType('FeelingsP', (_message.Message,), {
  'DESCRIPTOR' : _FEELINGSP,
  '__module__' : 'protocol_layer_pb2'
  # @@protoc_insertion_point(class_scope:FeelingsP)
  })
_sym_db.RegisterMessage(FeelingsP)


# @@protoc_insertion_point(module_scope)
