language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker run -d -p 27017:27017 mongo
  - docker run -d -p 5672:5672 rabbitmq

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest --cov-report term --cov=final
  
after_success:
  - codecov
